DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE nrel (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  fuel_type_code TEXT,
  station_name TEXT,
  street_address TEXT,
  intersection_directions TEXT,
  city TEXT,
  state_name TEXT,
  zip TEXT,
  plus4 FLOAT,
  station_phone TEXT,
  status_code TEXT,
  expected_date TEXT,
  groups_with_access_code TEXT,
  access_days_time TEXT,
  cards_accepted TEXT,
  bd_blends FLOAT,
  ng_fill_type_code FLOAT,
  ng_psi FLOAT,
  ev_level1_evse_num FLOAT,
  ev_level2_evse_num FLOAT,
  ev_dc_fast_count FLOAT,
  ev_other_info TEXT,
  ev_network TEXT,
  ev_network_web TEXT,
  geocode_status TEXT,
  latitude FLOAT,
  longitude FLOAT,
  date_last_confirmed TEXT,
  updated_at TEXT,
  owner_type_code TEXT,
  federal_agency_id FLOAT,
  federal_agency_name TEXT,
  open_date TEXT,
  hydrogen_status_link FLOAT,
  ng_vehicle_class FLOAT,
  lpg_primary FLOAT,
  e85_blender_pump FLOAT,
  ev_connector_types TEXT,
  country TEXT,
  hydrogen_is_retail FLOAT,
  access_code TEXT,
  access_detail_code TEXT,
  federal_agency_code TEXT,
  facility_type TEXT,
  cng_dispenser_num FLOAT,
  cng_on_site_renewable_source FLOAT,
  cng_total_compression_capacity FLOAT,
  cng_storage_capacity FLOAT,
  lng_on_site_renewable_source FLOAT,
  e85_other_ethanol_blends FLOAT,
  ev_pricing TEXT,
  lpg_nozzle_types FLOAT,
  hydrogen_pressures FLOAT,
  hydrogen_standards FLOAT,
  cng_fill_type_code FLOAT,
  cng_psi FLOAT,
  cng_vehicle_class FLOAT,
  lng_vehicle_class FLOAT,
  ev_on_site_renewable_source TEXT,
  restricted_access TEXT,
  rd_blends FLOAT,
  rd_blended_with_biodiesel FLOAT,
  rd_maximum_biodiesel_level FLOAT,
  nps_unit_name TEXT,
  cng_station_sells_renewable_natural_gas FLOAT,
  lng_station_sells_renewable_natural_gas FLOAT,
  maximum_vehicle_class TEXT,
  ev_workplace_charging TEXT
);